# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# Fonts:
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        15.0

# Opacity:
background_opacity         0.5
dynamic_background_opacity yes

# Padding:
window_padding_width 12

# Color Scheme:
background           #1e1e24
foreground           #d1d1d1
cursor               #ffffff
selection_background #444444
selection_foreground #ffffff

# Tones:
color0 #1e1e24
color8 #5e5e5e

color1 #e57373
color9 #ff8a80

color2  #81c784
color10 #b9f6ca

color3  #ffb74d
color11 #ffe082

color4  #64b5f6
color12 #80d8ff

color5  #ba68c8
color13 #ea80fc

color6  #4db6ac
color14 #a7ffeb

color7  #d1d1d1
color15 #ffffff

# Behaviour
enable_audio_bell no

url_color #0087bd
url_style curly

hide_window_decorations yes
confirm_os_window_close 0

